services:
  pytextify:
    build: .
    command: uvicorn pytextify.app:app --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app
  worker:
    build: .
    command: celery -A pytextify.tasks worker --loglevel=info
    volumes:
      - .:/app
  beat:
    build: .
    command: celery -A pytextify.tasks beat --loglevel=info
    volumes:
      - .:/app
